#!make
include .env.dev

run:
	NOTION_API_TOKEN=${NOTION_API_TOKEN} NOTION_TRANSACTION_TABLE_ID=${NOTION_TRANSACTION_TABLE_ID} NOTION_TO_SCHEDULE_TABLE_ID=${NOTION_TO_SCHEDULE_TABLE_ID} NOTION_BUDGETS_TABLE_ID=${NOTION_BUDGETS_TABLE_ID} NOTION_ACCOUNTS_TABLE_ID=${NOTION_ACCOUNTS_TABLE_ID} API_AUTH_TOKEN=${API_AUTH_TOKEN} go run "bin/$(bin)/main.go"